import { User, Transaction } from "../types";
import { toEnglishDigits } from "./shamsi";

export interface EmployeeBalanceSummary {
  staffId: string;
  staffName: string;
  contractType: "درصدی" | "اجاره‌ای" | "حقوق ثابت" | "نامشخص";
  totalGeneratedIncome: number;   // sum of درآمد خدمات + درآمد نوبت تخفیف‌دار transactions where relatedStaffId === staffId
  totalPaidOut: number;           // sum of حقوق پرسنل transactions where relatedStaffId === staffId
  totalOwedByStaff: number;       // for rent contracts: rent due
  netBalance: number;             // positive = salon owes staff, negative = staff owes salon
  lastTransactionDate?: string;
}

/**
 * Extracts a numeric value from a Persian/English text string.
 * Used to parse commission rate, base salary, or rent from contract.amount.
 */
export function parseContractAmount(amountStr: string | undefined): number {
  if (!amountStr) return 0;
  try {
    // Convert Persian digits to English digits
    const cleaned = toEnglishDigits(amountStr);
    // Keep only digits and decimal point
    const digitsOnly = cleaned.replace(/[^\d]/g, "");
    const parsed = parseInt(digitsOnly, 10);
    return isNaN(parsed) ? 0 : parsed;
  } catch (error) {
    console.error("Error parsing contract amount:", error);
    return 0;
  }
}

export function calculateEmployeeBalance(
  staff: User,
  transactions: Transaction[]
): EmployeeBalanceSummary {
  const staffId = staff.id;
  const staffName = staff.name;
  
  // Filter transactions related to this employee
  const relatedTx = transactions.filter(t => t.relatedStaffId === staffId);
  
  // Calculate total income generated by this artist (درآمد خدمات or درآمد نوبت تخفیف‌دار)
  const totalGeneratedIncome = relatedTx
    .filter(t => t.direction === "income" && (t.category === "درآمد خدمات" || t.category === "درآمد نوبت تخفیف‌دار"))
    .reduce((sum, t) => sum + t.amount, 0);

  // Calculate total salary/payout paid by the salon to the staff (حقوق پرسنل)
  const totalPaidOut = relatedTx
    .filter(t => t.direction === "cost" && t.category === "حقوق پرسنل")
    .reduce((sum, t) => sum + t.amount, 0);

  // Find the last transaction date
  let lastTransactionDate: string | undefined = undefined;
  if (relatedTx.length > 0) {
    const sorted = [...relatedTx].sort((a, b) => b.date.localeCompare(a.date));
    lastTransactionDate = sorted[0].date;
  }

  // Get contract info
  const contract = staff.contract;
  if (!contract) {
    return {
      staffId,
      staffName,
      contractType: "نامشخص",
      totalGeneratedIncome,
      totalPaidOut,
      totalOwedByStaff: 0,
      netBalance: 0, // No contract, can't estimate net balance definitively
      lastTransactionDate
    };
  }

  const parsedAmount = parseContractAmount(contract.amount);
  let netBalance = 0;
  let totalOwedByStaff = 0;

  switch (contract.contractType) {
    case "درصدی": {
      // Amount is commission percentage (e.g. 40 or 40%)
      const rate = parsedAmount > 0 && parsedAmount <= 100 ? parsedAmount / 100 : 0.50; // default 50%
      const earnedCommission = Math.round(totalGeneratedIncome * rate);
      netBalance = earnedCommission - totalPaidOut;
      break;
    }
    case "حقوق ثابت": {
      // Amount is fixed salary
      const baseSalary = parsedAmount > 0 ? parsedAmount : 12000000; // default 12,000,000 if not parseable
      netBalance = baseSalary - totalPaidOut;
      break;
    }
    case "اجاره‌ای": {
      // Amount is rent the staff owes to the salon
      const rentOwed = parsedAmount > 0 ? parsedAmount : 5000000; // default 5,000,000 if not parseable
      totalOwedByStaff = rentOwed;
      // Net balance is: what they paid - what they owe. 
      // In this setup, totalPaidOut represents payments made by the artist for rent (or logged costs)
      // Usually, the salon logs "rights/salary/payouts" towards staff, or artist pays rent.
      // If the artist paid the rent to salon (represented as a payout/ledger cost or vice versa), 
      // let's follow the specification: netBalance = totalPaidOut - rentOwed
      netBalance = totalPaidOut - rentOwed;
      break;
    }
    default:
      netBalance = 0;
  }

  return {
    staffId,
    staffName,
    contractType: contract.contractType,
    totalGeneratedIncome,
    totalPaidOut,
    totalOwedByStaff,
    netBalance,
    lastTransactionDate
  };
}
